parametersManagerConfig:
  parameterSetList: "./Configs_ParameterSetList/parameterSetList_MuonCos.yaml"

showEventBreakdown: true

enableStatThrowInToys: false

enableEventMcThrow: false

debugPrintLoadedEvents: true

fitSampleSetConfig: "./Configs_FitSampleSet/fitSamples_RecoMuonCos.yaml"

plotGeneratorConfig: "./Configs_PlotGenerator/plotConfigs_RecoMuonCos.yaml"


