# Config for gundamFitter: starting based on screenshots on sbn-doc-32028... let's see

outputFolder: "./output/"
minGundamVersion: 1.9.0

fitterEngineConfig:

  # minimizer
  minimizerConfig: "./Configs_Minimizer/default_minimizer.yaml"

  # likelihoodInterface
  likelihoodInterfaceConfig:

    # jointProbability
    jointProbabilityConfig:
      type: "PoissonLLH"

    # dataSetManager
    dataSetManagerConfig:

      propagatorConfig: "./Configs_Propagator/propagatorConfig_RecoMuonCos.yaml"
      dataSetList: "./Configs_DataSetList/dataSetListConfig_FakeData.yaml"


  # listing local configs 

  ## "_enablePca_" is set by {"enablePca"}, {"runPcaCheck"}, {"fixGhostFitParameters"}
  ## - default: false
  enablePca: true

  ## "_pcaDeltaChi2Threshold_" is set by {"ghostParameterDeltaChi2Threshold"}, {"pcaDeltaChi2Threshold"}
  ## - default: 1E-6
  pcaDeltaChi2Threshold: 1E-4

  ## "_enablePreFitScan_" is set by "enablePreFitScan"
  ## - default: false
  enablePreFitScan: false

  ## "_enablePostFitScan_" is set by "enablePostFitScan"
  ## - default: false
  enablePostFitScan: false

  ## "_enablePreFitToPostFitLineScan_" is set by "enablePreFitToPostFitLineScan"
  ## - default: true

  ## "_generateSamplePlots_" is set by "generateSamplePlots"
  ## - default: true

  ## "_generateOneSigmaPlots_" is set by "generateOneSigmaPlots"
  ## - default: false

  ## "_doAllParamVariations_" is set by "enableParamVariations"
  ## - default: false

  ## "_allParamVariationsSigmas_" is set by {"paramVariationsSigmas"}, {"allParamVariations"}
  ## - default: empty vector

  ## "_scaleParStepWithChi2Response_" is set by "scaleParStepWithChi2Response"
  ## - default: false

  ## "_parStepGain_" is set by "parStepGain"
  ## - default: 0.1

  ## "_throwMcBeforeFit_" is set by "throwMcBeforeFit"
  ## - default: false

  ## "_throwGain_" is set by "throwMcBeforeFitGain"
  ## - default: 1.

  ## "_savePostfitEventTrees_" is set by "savePostfitEventTrees"
  ## - default: false







